# Generated by Django 4.2.2 on 2023-07-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studid', models.IntegerField()),
                ('studname', models.CharField(max_length=50)),
                ('studemail', models.EmailField(max_length=100)),
                ('studdetail', models.CharField(max_length=50)),
            ],
        ),
    ]
