# Generated by Django 4.2.2 on 2023-07-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=50)),
                ('stuemail', models.EmailField(max_length=40)),
                ('stupass', models.CharField(max_length=30)),
            ],
        ),
    ]
